completed css-two-column-layout challenge.
david-s-song/c1021-code-solutions pull request #20
Opened 2021-10-11 02:11 UTC by david-s-song

![css-two-column-layout](https://user-images.githubusercontent.com/90665895/136723620-ef529627-56e3-43ee-8f26-6191e3ffdece.png)

2021-10-11 17:20 UTC, codingcodymiller requested changes
Hey David! This is looking pretty good, but please revise this to make proper use of layout classes, such as `container`, `row`, and `column` classes. This works, but you should really be practicing setting up layout classes for yourself, they will be crucial as you start to deal with larger CSS tasks in projects.

2021-10-12 07:52 UTC, david-s-song commented
![css two column layout redo](https://user-images.githubusercontent.com/90665895/136914836-f97ea3e4-ac6d-4964-91b9-666d265b5532.png)

2021-10-12 18:27 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +.column-one-fourth {
This class name isn't accurate. A fourth would be `25%`. You should name this something like `column-40`. **However**, I think this is actually something that should be a `column-half`. I suggest you revise this to `width: 50%` and make adjustments elsewhere to make that measurement correct, you may need to add `padding` to these elements to constrict their content a bit.

2021-10-12 20:19 UTC, david-s-song commented
![css two column redo](https://user-images.githubusercontent.com/90665895/137023422-330d97a9-80b0-4032-ac25-d18916da1c49.png)

2021-10-13 18:21 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  margin-right: auto;
![image](https://user-images.githubusercontent.com/32880187/137190966-56e68c26-bd50-4daa-afbd-fc77511c9dd5.png)

2021-10-13 18:22 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  padding-left: 5%;
![image](https://user-images.githubusercontent.com/32880187/137191031-e79928da-ea2d-44da-bf2d-90023f8a9813.png)

2021-10-13 18:22 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  display: flex;
If you are applying `display: flex` to a column class, that usually means that the `column` should contain a `row` class element. That is the purpose of the `row` class, to make flex containers

2021-10-13 18:22 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  flex-shrink: 0;
Why?

2021-10-16 08:29 UTC, david-s-song commented
<img width="767" alt="css-two-column-redo" src="https://user-images.githubusercontent.com/90665895/137580511-aada155d-d8af-4969-945b-4a3132f69cf1.png">

2021-10-18 17:49 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +  position: relative;
This is still a bunch of excess styling on your `column` class. COlumn classes should only include a `width` or `flex-basis`. You should make an additional class you can add along with the `column-half` class.

2021-10-22 00:17 UTC, merged