completed css-four-column-layout challenge.
david-s-song/c1021-code-solutions pull request #31
Opened 2021-10-14 06:35 UTC by david-s-song

![Screen Shot 2021-10-13 at 11 30 25 PM](https://user-images.githubusercontent.com/90665895/137264405-2c0b68b4-58f1-4730-a13d-c97d041465e0.png)

2021-10-14 17:11 UTC, codingcodymiller requested changes
Good start! One note to get you started:

2021-10-14 17:11 UTC, codingcodymiller commented on css-four-column-layout/index.html
> +  </footer>
I can see why you broke these pieces of the layout into rows based on how they look in terms of "layout", but this makes the content of each column seem separate from one another. You should have one `row` with four `columns`, each of which holds the image, icon, and text for that column

2021-10-16 09:15 UTC, david-s-song commented
<img width="1000" alt="css four column layout redo" src="https://user-images.githubusercontent.com/90665895/137581959-3712a458-6524-460e-89be-ecdc32c0ad47.png">

2021-10-19 00:15 UTC, codingcodymiller commented on css-four-column-layout/index.html
> +    <div class="column-full">
Instead of one `column-full`, you should make four `column-fourth` elements, and create a class with appropriate styling for it

2021-10-20 15:38 UTC, david-s-song commented
![css four column layout redo redo](https://user-images.githubusercontent.com/90665895/138125272-5bba1563-312f-4ef4-b822-d4be05ed3060.png)

2021-10-25 18:45 UTC, merged