completed object-manipulation-1.
david-s-song/c1021-code-solutions pull request #53
Opened 2021-10-30 20:33 UTC by david-s-song

<img width="1401" alt="Object Mani 1" src="https://user-images.githubusercontent.com/90665895/139557614-fc30af7e-55fd-42c0-a4a0-8d939bb7ce19.png">

2021-11-01 16:52 UTC, codingcodymiller requested changes

2021-11-01 16:52 UTC, codingcodymiller commented on object-manipulation-1/src/to-object.js
> +  for (var i = 0; i < keyValuePair.length; i++) {
This loop is unnecessary

2021-11-01 16:52 UTC, codingcodymiller commented on object-manipulation-1/src/to-object.js
> +  } return newObject;
Make sure `return` statements are on their own line, they should not be on the same line as a closing brace

2021-11-02 05:27 UTC, david-s-song commented
<img width="1401" alt="Object Mani 1" src="https://user-images.githubusercontent.com/90665895/139791366-a8d7eef8-4bb6-4c74-aecc-9c3611d373d4.png">

2021-11-02 23:27 UTC, codingcodymiller approved these changes

2021-11-04 05:05 UTC, merged