Array manipulation 1
david-s-song/c1021-code-solutions pull request #54
Opened 2021-10-30 23:22 UTC by david-s-song

<img width="1362" alt="array mani 1" src="https://user-images.githubusercontent.com/90665895/139561042-fbdd3608-a6a3-44d8-aed2-aae06f03b1c1.png">

2021-11-01 16:38 UTC, codingcodymiller requested changes

2021-11-01 16:38 UTC, codingcodymiller commented on array-manipulation-1/src/initial.js
> +    if (i !== array.length - 1) {
Instead of having this conditional in the loop, you can adjust your condition to stop sooner, and remove the need for this.

2021-11-01 16:38 UTC, codingcodymiller commented on array-manipulation-1/src/tail.js
> +    if (i !== 0) {
Instead of having this conditional in the loop, you can adjust your initialization to start at `1` rather than. `0`, and remove the need for this.

2021-11-02 04:57 UTC, david-s-song commented
<img width="1362" alt="array mani 1" src="https://user-images.githubusercontent.com/90665895/139789101-840aba26-4053-4b6f-b02b-e7785405667a.png">

2021-11-02 22:28 UTC, codingcodymiller approved these changes

2021-11-03 16:52 UTC, merged